### ISSUE TITLE
postgresql执行SQL错误，sql语句在mysql中正常，

### ISSUE THREAD

**Issue by qq670582339** [Dreampie/Resty#17]
表
```sql
CREATE SEQUENCE public.sec_user_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE public.sec_user_id_seq
  OWNER TO postgres;

CREATE TABLE public.sec_user
(
  id integer NOT NULL DEFAULT nextval('sec_user_id_seq'::regclass),
  sid integer NOT NULL,
  username character varying(50) NOT NULL,
  providername character varying(50) NOT NULL,
  email character varying(200),
  phone character varying(200),
  password character varying(200) NOT NULL,
  avatar_url character varying(255),
  first_name character varying(10),
  last_name character varying(10),
  full_name character varying(20),
  created_at timestamp without time zone NOT NULL,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT sec_user_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.sec_user
  OWNER TO postgres;

INSERT INTO sec_user(id,sid,username, providername, email, phone, password, avatar_url, first_name, last_name, full_name, created_at) VALUES (1,2,'admin','shengmu','wangrenhui1990@gmail.com','18611434500','57827590596df8a8113116977059c7578d652b95ec123c23e89800ebbffd384e1eb17c8f8eb3d957784ad5ee54e1ff065cd3df0a491106940094bbc9adcd644b','','管理员','圣牧','圣牧.管理员',current_timestamp);
```

```java
16-01-27 12:19:36.067 [qtp211031000-14] DEBUG druid.sql.Statement - {conn-10010, pstmt-20000} Parameters : [admin]
16-01-27 12:19:36.067 [qtp211031000-14] DEBUG druid.sql.Statement - {conn-10010, pstmt-20000} Types : [VARCHAR]
16-01-27 12:19:36.083 [qtp211031000-14] ERROR druid.sql.Statement - {conn-10010, pstmt-20000} execute error. SELECT * FROM sec_user WHERE username=? AND deleted_at IS NULL LIMIT 1 OFFSET 0
org.postgresql.util.PSQLException: 错误: 语法错误 在 "RETURNING" 或附近的
  位置：82
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:472) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:386) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2714) [druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.wall.WallFilter.preparedStatement_executeQuery(WallFilter.java:609) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2711) [druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2711) [druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2711) [druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:132) [druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227) [druid-1.0.13.jar:1.0.13]
	at cn.dreampie.orm.Base.find(Base.java:512) [resty-orm-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.orm.Base.findFirst(Base.java:539) [resty-orm-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.orm.Base.findFirstBy(Base.java:1100) [resty-orm-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.config.MyAuthenticateService.getPrincipal(MyAuthenticateService.java:29) [classes/:na]
	at cn.dreampie.security.credential.Credentials.getPrincipal(Credentials.java:138) [resty-security-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.Subject.login(Subject.java:77) [resty-security-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.Subject.login(Subject.java:132) [resty-security-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.resource.SessionResource.login(SessionResource.java:36) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:95) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.transaction.TransactionInterceptor.intercept(TransactionInterceptor.java:64) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:37) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.cache.CacheInterceptor.intercept(CacheInterceptor.java:83) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:67) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:82) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:550) [jetty-security-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1128) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1062) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.Server.handle(Server.java:507) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:237) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:240) [jetty-io-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:93) [jetty-io-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:53) [jetty-io-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.produceAndRun(ExecuteProduceRun.java:191) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.run(ExecuteProduceRun.java:126) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:641) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:559) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
16-01-27 12:19:36.083 [qtp211031000-14] DEBUG druid.sql.Statement - {conn-10010, pstmt-20000} clearParameters. 
16-01-27 12:19:36.083 [qtp211031000-14] DEBUG com.alibaba.druid.pool.PreparedStatementPool - {conn-10010, pstmt-20000} enter cache
16-01-27 12:19:36.083 [qtp211031000-14] DEBUG druid.sql.Connection - {conn-10010} pool-recycle
16-01-27 12:19:36.083 [qtp211031000-14] ERROR cn.dreampie.route.core.Route - Route method invoke error.
cn.dreampie.orm.exception.DBException: 错误: 语法错误 在 "RETURNING" 或附近的
  位置：82
	at cn.dreampie.orm.Base.find(Base.java:517) ~[resty-orm-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.orm.Base.findFirst(Base.java:539) ~[resty-orm-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.orm.Base.findFirstBy(Base.java:1100) ~[resty-orm-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.config.MyAuthenticateService.getPrincipal(MyAuthenticateService.java:29) ~[classes/:na]
	at cn.dreampie.security.credential.Credentials.getPrincipal(Credentials.java:138) ~[resty-security-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.Subject.login(Subject.java:77) ~[resty-security-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.Subject.login(Subject.java:132) ~[resty-security-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.resource.SessionResource.login(SessionResource.java:36) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:95) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.transaction.TransactionInterceptor.intercept(TransactionInterceptor.java:64) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:37) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.cache.CacheInterceptor.intercept(CacheInterceptor.java:83) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:191) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:67) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:82) [resty-route-1.2.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:550) [jetty-security-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1128) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1062) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.Server.handle(Server.java:507) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:237) [jetty-server-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:240) [jetty-io-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:93) [jetty-io-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:53) [jetty-io-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.produceAndRun(ExecuteProduceRun.java:191) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceRun.run(ExecuteProduceRun.java:126) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:641) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:559) [jetty-util-9.3.0.M2.jar:9.3.0.M2]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: org.postgresql.util.PSQLException: 错误: 语法错误 在 "RETURNING" 或附近的
  位置：82
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:472) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:386) ~[postgresql-9.4.1207.jar:9.4.1207.jre7]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2714) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.wall.WallFilter.preparedStatement_executeQuery(WallFilter.java:609) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2711) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2711) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2711) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:132) ~[druid-1.0.13.jar:1.0.13]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227) ~[druid-1.0.13.jar:1.0.13]
	at cn.dreampie.orm.Base.find(Base.java:512) ~[resty-orm-1.2.0-SNAPSHOT.jar:na]
	... 51 common frames omitted
16-01-27 12:19:36.083 [qtp211031000-14] WARN  cn.dreampie.route.holder.DefaultExceptionHolder - Request "POST /api/v1.2/sessions" error : 500 "错误: 语法错误 在 \"RETURNING\" 或附近的\n  位置：82"
```

**Comment by qq670582339** [comment]
上面的为postgresql建表语句，INSERT INTO sec_user(id,sid,username, providername, email, phone, password, avatar_url, first_name, last_name, full_name, created_at) VALUES (1,2,'admin','shengmu','wangrenhui1990@gmail.com','18611434500','57827590596df8a8113116977059c7578d652b95ec123c23e89800ebbffd384e1eb17c8f8eb3d957784ad5ee54e1ff065cd3df0a491106940094bbc9adcd644b','','管理员','圣牧','圣牧.管理员',current_timestamp);
后面的是错误
