### ISSUE TITLE
QuartzPlugin启动报错：`org.quartz.SchedulerConfigException: Thread count must be > 0`

### ISSUE THREAD

**Issue by zhaoyunfei9271** [Dreampie/Resty#21]
```java
SEVERE:   WebModule[/isofoo_api]Exception starting filter RestyFilter
java.lang.InstantiationException
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:135)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:5329)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5974)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:691)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2286)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1932)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:243)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: javax.servlet.ServletException: Can't start quartz plugin.
	at cn.dreampie.route.RestyFilter.init(RestyFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:275)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:131)
	... 28 more
Caused by: cn.dreampie.quartz.exception.QuartzException: Can't start quartz plugin.
	at cn.dreampie.quartz.QuartzPlugin.start(QuartzPlugin.java:83)
	at cn.dreampie.route.ConfigIniter.startPlugins(ConfigIniter.java:56)
	at cn.dreampie.route.ConfigIniter.<init>(ConfigIniter.java:21)
	at cn.dreampie.route.RestyIniter.<init>(RestyIniter.java:24)
	at cn.dreampie.route.RestyFilter.init(RestyFilter.java:43)
	... 30 more
Caused by: org.quartz.SchedulerConfigException: Thread count must be > 0
	at org.quartz.simpl.SimpleThreadPool.initialize(SimpleThreadPool.java:242)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1288)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519)
	at cn.dreampie.quartz.QuartzPlugin.start(QuartzPlugin.java:76)
	... 34 more
```

**Comment by Dreampie** [comment]
注意错误信息：
```java
org.quartz.SchedulerConfigException: Thread count must be > 0
```
标题 准确一些

把quartzPlugin 去掉试试

**Comment by zhaoyunfei9271** [comment]
#是否启用该任务
job.daily.enable=false

**Comment by Dreampie** [comment]
这个应该是quartz的配置问题 ，不是任务的问题

https://github.com/Dreampie/Resty/blob/master/resty-quartz/src/main/resources/quartz/quartz.properties

```java
org.quartz.threadPool.threadCount
```

**Comment by zhaoyunfei9271** [comment]
额，难道是。我启动多次然后意外中止的原因？

**Comment by Dreampie** [comment]
quartz的问题的话  只能搜索一下相关的内容  或者在stackoverflow上 找找

http://stackoverflow.com/questions/35723948/what-is-the-quartz-default-thread-count

**Comment by zhaoyunfei9271** [comment]
好哒，谢谢了
