### ISSUE TITLE
使用了事务注解没生效，麻烦看看是什么情况

### ISSUE THREAD

**Issue by weimo123** [Dreampie/Resty#33]
代码帖在下面，第一次用，不知道怎么格式化。将就下了。我在service层加了注解，然后用的时候，比如说在执行Log这个对象保存的时候异常了，但是之前的User保存还是被执行了。不知道是不是哪个地方需要改改，求解

```java
- service层
@Transaction
public boolean login(User u);

- serviceImpl层
public boolean login(User u) {
  boolean result = u.update();
  if(result){
    result = new Log().set("user_id", u.get("id")).set("operator_id", u.get("operator_id")).set("create_date", new Date()).save();
	}
	return result;
}

- resource
@POST(value="/login",des="用户登陆")
public String login(String username,String password,String password_) {
		  try {
			  User user = new User().set("login_name", username).set("login_pwd", password);
			  boolean result = userService.login(user);
			  if(result){
				  return "OK";
			  }else{
				  return "No";
			  }
		  } catch (Exception e) {
			  e.printStackTrace();
			  return "No";
		  }
	  }
```

**Comment by Dreampie** [comment]
service的创建方式是怎么样的？

**Comment by weimo123** [comment]
private UserService userService = AspectFactory.newInstance(new UserServiceImpl(), new TransactionAspect());

**Comment by Dreampie** [comment]
错误信息 有没有Transaction相关的，或者你贴一下

**Comment by weimo123** [comment]
好像没有哦，我是特地在Log对象保存的时候写了一个不存在的字段，然后抛数据库的异常，后面看到User对象还是被修改掉了

**Comment by Dreampie** [comment]
`@Transaction` 是cn.dreampie下的包吗，数据源是不是一个

**Comment by weimo123** [comment]
是的。import cn.dreampie.orm.transaction.Transaction; 
数据源只用了一个
public void configPlugin(PluginLoader pluginLoader) {
    //数据库
    C3p0DataSourceProvider cdsp = new C3p0DataSourceProvider("default");
    ActiveRecordPlugin activeRecordCdsp = new ActiveRecordPlugin(cdsp);
    activeRecordCdsp.addIncludePackages("com.xx.api.resource");
    pluginLoader.add(activeRecordCdsp);
｝

**Comment by Dreampie** [comment]
确定数据库是否支持事务，如果支持的话，我会模拟一段代码来测试，之后会在这儿回复你

**Comment by weimo123** [comment]
嗯，我看看，没想到这个点。

**Comment by weimo123** [comment]
我刚刚看了下数据库，支持事务的

**Comment by weimo123** [comment]
事务代码有报错。我贴下。
cn.dreampie.orm.exception.TransactionException
	at cn.dreampie.orm.transaction.TransactionAspect.aspect(TransactionAspect.java:58)
	at cn.dreampie.orm.aspect.AspectHandler.invoke(AspectHandler.java:64)
	at cn.dreampie.orm.aspect.AspectHandler.invoke(AspectHandler.java:60)
	at com.sun.proxy.$Proxy14.login(Unknown Source)
	at cc.weimo.api.resource.SessionResource.adminLogin(SessionResource.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:606)
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:95)
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:187)
	at cn.dreampie.route.interceptor.transaction.TransactionInterceptor.intercept(TransactionInterceptor.java:64)
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55)
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:187)
	at cn.dreampie.route.cache.CacheInterceptor.intercept(CacheInterceptor.java:83)
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:55)
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:187)
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:67)
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102)
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:82)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cn.dreampie.orm.aspect.AspectHandler.invoke(AspectHandler.java:66)
	at cn.dreampie.orm.transaction.TransactionAspect.aspect(TransactionAspect.java:43)

	... 40 more
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy13.save(Unknown Source)
	at cc.weimo.api.resource.admin.service.impl.AdminServiceImpl.login(AdminServiceImpl.java:84)
	... 46 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cn.dreampie.orm.aspect.AspectHandler.invoke(AspectHandler.java:66)
	at cn.dreampie.orm.transaction.TransactionAspect.aspect(TransactionAspect.java:66)
	at cn.dreampie.orm.aspect.AspectHandler.invoke(AspectHandler.java:64)
	at cn.dreampie.orm.aspect.AspectHandler.invoke(AspectHandler.java:60)

	... 48 more

后面的数据库异常，我改了字段。
Caused by: cn.dreampie.orm.exception.DBException: Unknown column 'id' in 'field list'
	at cn.dreampie.orm.Base.save(Base.java:712)
	at cc.weimo.api.resource.admin.service.impl.AdminLoginLogServiceImpl.save(AdminLoginLogServiceImpl.java:36)
	... 56 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id' in 'field list'

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at cn.dreampie.orm.Base.save(Base.java:707)
	... 57 more

**Comment by Dreampie** [comment]
嗯 好  我先测一下

**Comment by Dreampie** [comment]
基于resty-example代码测试，没有发现该问题，事务能正常回滚
操作流程：

修改UserServiceImpl模拟两次提交，第二次保存不存在的属性导致报错：
```java
public class UserServiceImpl implements UserService {

  public User save(User u) {
    UserInfo userInfo = null;
    if (u.get("user_info") == null) {
      userInfo = new UserInfo().set("gender", 0);
    } else {
      userInfo = u.get("user_info");
    }
    if (u.set("providername", "x").set("password", "123").set("sid", "2").save()) {
      userInfo.set("user_id", u.get("id"));
      userInfo.save();
    }
    update(u);
    if (u != null) {
      new User().set("xxid","xx").save();
    }
    return u;
  }

  public User update(User u) {
    u.update();
    return u;
  }
}

```
启动server，run test目录下的ClientTest.testSave() 方法，结果数据库没有产生数据 ，整个user的数据事务正常，可以看一下，有问题联系我

**Comment by weimo123** [comment]
我刚刚也测试了，的确可以。如果要开启事务，需要在哪些地方做修改呢？我现在再去跟example去对比下

**Comment by weimo123** [comment]
已经可以了。还是当时疏忽，百度上查了下怎么查询数据库是否支持事务，用了个SHOW ENGINES;看后是支持的。刚刚到表里面看了下，表的引擎并不是InnoDB，后面把表的引擎全改了，现在已经支持事务了。谢谢，非常感谢帮助我这么多。提前祝端午节快乐！
