### ISSUE TITLE
批量上传图片出错

### ISSUE THREAD

**Issue by T-baby** [Dreampie/Resty#54]
下面的路径是我修改过的版本ICEREST的，但是涉及到文件上传的部分没有经过修改
````java
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class
	at com.cybermkd.route.core.Route.parseFormParams(Route.java:546) ~[ICEREST-1.0.1.3.jar:na]
	at com.cybermkd.route.core.Route.match(Route.java:278) ~[ICEREST-1.0.1.3.jar:na]
	at com.cybermkd.route.core.RouteHandler.handle(RouteHandler.java:47) [ICEREST-1.0.1.3.jar:na]
	at com.cybermkd.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) [ICEREST-1.0.1.3.jar:na]
	at com.cybermkd.route.IceFilter.doFilter(IceFilter.java:90) [ICEREST-1.0.1.3.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:9.0.0.M9]
	at com.cybermkd.filter.WafFilter.doFilter(WafFilter.java:44) [ICEREST-1.0.1.3.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:9.0.0.M9]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [catalina.jar:9.0.0.M9]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) [tomcat-coyote.jar:9.0.0.M9]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.0.M9]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-coyote.jar:9.0.0.M9]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-coyote.jar:9.0.0.M9]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.0.M9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.0.M9]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

````

**Comment by Dreampie** [comment]
https://github.com/Dreampie/Resty/blob/master/resty-example/src/main/java/cn/dreampie/resource/TestResource.java

已经添加批量上传文件的例子，试试index.html

**Comment by T-baby** [comment]
已解决，经查验是由于与kotlin不兼容导致。解决办法是含有批量上传的controller用原生java写即可解决。
