### ISSUE TITLE
运行resty-example下的pom.xml->tomcat6-maven-plugin:run,启动example程序，报错无法启动。

### ISSUE THREAD

**Issue by dxxfire** [Dreampie/Resty#7]
java.lang.ClassCastException: com.alibaba.druid.support.http.WebStatFilter cannot be cast to javax.servlet.Filter和 The web application [/resty-example] appears to have started a thread na
med [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.这2个错误，请问该如何解决。
JDK为1.7.0_21
MySql为mysql-5.6.25-winx64

F:\it\Resty\resty-example>mvn clean tomcat:run
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
cn.dreampie:resty-example:war:1.0
[WARNING] 'version' contains an expression but should be a constant. @ cn.dreamp
ie:resty-example:${project.parent.version}, F:\it\Resty\resty-example\pom.xml, l
ine 12, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building resty-example 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ resty-example ---
[INFO] Deleting F:\it\Resty\resty-example\target
[INFO]
[INFO] >>> tomcat-maven-plugin:1.1:run (default-cli) > compile @ resty-example >
>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ resty-exam
ple ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ resty-example -
--
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to F:\it\Resty\resty-example\target\classes
[WARNING] /F:/it/Resty/resty-example/src/main/java/cn/dreampie/config/MyAuthenti
cateService.java: F:\it\Resty\resty-example\src\main\java\cn\dreampie\config\MyA
uthenticateService.java使用了未经检查或不安全的操作。
[WARNING] /F:/it/Resty/resty-example/src/main/java/cn/dreampie/config/MyAuthenti
cateService.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO]
[INFO] <<< tomcat-maven-plugin:1.1:run (default-cli) < compile @ resty-example <
<<
[INFO]
[INFO] --- tomcat-maven-plugin:1.1:run (default-cli) @ resty-example ---
[INFO] Running war on http://localhost:8080/resty-example
[INFO] Creating Tomcat server configuration at F:\it\Resty\resty-example\target\
tomcat
七月 18, 2015 11:05:37 下午 org.apache.catalina.startup.Embedded start
INFO: Starting tomcat server
七月 18, 2015 11:05:37 下午 org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/6.0.29
23:05:38,142 |-INFO in ch.qos.logback.classic.LoggerContext[resty-example] - Cou
ld NOT find resource [logback.groovy]
23:05:38,142 |-INFO in ch.qos.logback.classic.LoggerContext[resty-example] - Cou
ld NOT find resource [logback-test.xml]
23:05:38,142 |-INFO in ch.qos.logback.classic.LoggerContext[resty-example] - Fou
nd resource [logback.xml] at [file:/F:/it/Resty/resty-example/target/classes/log
back.xml]
23:05:38,180 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction -
 debug attribute not set
23:05:38,193 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - S
etting logger context name as [resty-example]
23:05:38,193 |-WARN in ch.qos.logback.core.joran.action.PropertyAction - [substi
tutionProperty] element has been deprecated. Please use the [property] element i
nstead.
23:05:38,195 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About t
o instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
23:05:38,198 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming
appender as [STDOUT]
23:05:38,244 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This append
er no longer admits a layout as a sub-component, set an encoder instead.
23:05:38,244 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure c
ompatibility, wrapping your layout in LayoutWrappingEncoder.
23:05:38,244 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also ht
tp://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
23:05:38,244 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About t
o instantiate appender of type [ch.qos.logback.core.FileAppender]
23:05:38,246 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming
appender as [FILE]
23:05:38,248 |-WARN in ch.qos.logback.core.FileAppender[FILE] - This appender no
 longer admits a layout as a sub-component, set an encoder instead.
23:05:38,248 |-WARN in ch.qos.logback.core.FileAppender[FILE] - To ensure compat
ibility, wrapping your layout in LayoutWrappingEncoder.
23:05:38,248 |-WARN in ch.qos.logback.core.FileAppender[FILE] - See also http://
logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
23:05:38,248 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is
 set to [./logs/resty-example.log]
23:05:38,250 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Se
tting level of ROOT logger to DEBUG
23:05:38,250 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Atta
ching appender named [STDOUT] to Logger[ROOT]
23:05:38,251 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Atta
ching appender named [FILE] to Logger[ROOT]
23:05:38,251 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction -
 End of configuration.
23:05:38,251 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@11220055 -
 Registering current configuration as safe fallback point

七月 18, 2015 11:05:38 下午 org.apache.catalina.core.StandardContext filterStart

SEVERE: Exception starting filter DruidWebStatFilter
java.lang.ClassCastException: com.alibaba.druid.support.http.WebStatFilter canno
t be cast to javax.servlet.Filter
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(Applicatio
nFilterConfig.java:275)
        at org.apache.catalina.core.ApplicationFilterConfig.setFilterDef(Applica
tionFilterConfig.java:422)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFi
lterConfig.java:115)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.
java:4001)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4
651)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)

        at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)

        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445
)
        at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
        at org.codehaus.mojo.tomcat.AbstractRunMojo.startContainer(AbstractRunMo
jo.java:558)
        at org.codehaus.mojo.tomcat.AbstractRunMojo.execute(AbstractRunMojo.java
:255)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)

七月 18, 2015 11:05:38 下午 org.apache.catalina.core.StandardContext filterStart

SEVERE: Exception starting filter RestyFilter
java.lang.ClassCastException: cn.dreampie.route.RestyFilter cannot be cast to ja
vax.servlet.Filter
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(Applicatio
nFilterConfig.java:275)
        at org.apache.catalina.core.ApplicationFilterConfig.setFilterDef(Applica
tionFilterConfig.java:422)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFi
lterConfig.java:115)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.
java:4001)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4
651)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)

        at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)

        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445
)
        at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
        at org.codehaus.mojo.tomcat.AbstractRunMojo.startContainer(AbstractRunMo
jo.java:558)
        at org.codehaus.mojo.tomcat.AbstractRunMojo.execute(AbstractRunMojo.java
:255)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)

七月 18, 2015 11:05:38 下午 org.apache.catalina.core.StandardContext start
SEVERE: Error filterStart
七月 18, 2015 11:05:38 下午 org.apache.catalina.core.StandardContext start
SEVERE: Context [/resty-example] startup failed due to previous errors
七月 18, 2015 11:05:38 下午 org.apache.catalina.loader.WebappClassLoader clearRe
ferencesJdbc
SEVERE: The web application [/resty-example] registered the JBDC driver [com.ali
baba.druid.proxy.DruidDriver] but failed to unregister it when the web applicati
on was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unre
gistered.
七月 18, 2015 11:05:38 下午 org.apache.catalina.loader.WebappClassLoader clearRe
ferencesJdbc
SEVERE: The web application [/resty-example] registered the JBDC driver [com.ali
baba.druid.mock.MockDriver] but failed to unregister it when the web application
 was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregi
stered.
七月 18, 2015 11:05:38 下午 org.apache.catalina.loader.WebappClassLoader clearRe
ferencesJdbc
SEVERE: The web application [/resty-example] registered the JBDC driver [com.mys
ql.jdbc.Driver] but failed to unregister it when the web application was stopped
. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
七月 18, 2015 11:05:38 下午 org.apache.catalina.loader.WebappClassLoader clearRe
ferencesJdbc
SEVERE: The web application [/resty-example] registered the JBDC driver [com.mys
ql.fabric.jdbc.FabricMySQLDriver] but failed to unregister it when the web appli
cation was stopped. To prevent a memory leak, the JDBC Driver has been forcibly
unregistered.
七月 18, 2015 11:05:38 下午 org.apache.catalina.loader.WebappClassLoader clearRe
ferencesThreads
SEVERE: The web application [/resty-example] appears to have started a thread na
med [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.

**Comment by Dreampie** [comment]
这是druid错误信息，你先把filter去掉试试
